language: node_js
node_js:
  - '8'
  - '10'
  - '11'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "qTIhAxd8MiVjplrQhagSnMp6BbWq9MN7/dyp/DjO5kWcCd3KdmaDtEvXZrPQdGhQYAU2qsE7x+gL/PJmr1XHBRzwLh5CjFMSYoeNrq9v0SgGSAFUnjMFybAg2wZhw/0pj7xL12sfRs/XrbdFNfTUkBdNpwGNuqA4f4qAgiYdCZtbUV07RaJORhbBoMydDyipYI7/AEYyxGXI9QS3SIHFUdqveMOenNhLjKnThfkRiiKk920ZzK6t0ffnthn81H8RjMnf6RASlb+cw26Eu9gzRWl1uL95SBJiO964ArEgKpvRS7LtwppKkov0C9CxdMHNCnDNuKtUNVPpkfaKG/k4Q21hwfS+SHHvOBx2VZoEGmxqyoXz7WThO2L46VFuT30jRn6f6x3dTPxpMVkha0sMMZM5hS+duIoUD0YyVQWOHYkfHGW2v33U/pLH8+v4pEAgyYhCFJons26lZC0tRxKbSwWN2fnCZLhC+7BZIJE33Z9OBuKeRiDCwZOcgDqHqtPTsCddySHKdLqq1dCXRolor89hs56DsV2iUwBKJ7JTHegVpotaaigc7lLyPhQYzsEZ2ym9Ec2MGeXhveywYDw6evjc7bIsonVFNzjT2Ht1F/mQPVyIDIsPP2vJUeee++JYoSjCcjfdIpkkJV92srFFSnDqV0HY1+ZpKzqUeRqYpBA="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/managed-integration-example
    node: '8'
